### ISSUE TITLE
Erros e Metas para a finalização do projeto

### ISSUE THREAD

**Issue by barbosaGdev** [barbosaGdev/TCC-samu#4]
Falta ajusta o update da noticia e do curso de acordo com o novo modelo do banco de dados.

Está tendo um erro de exibição e inserção dos vídeos secundários nos cursos

**Comment by Mysfer** [comment]
Está tendo um erro de exibição e inserção dos vídeos secundários nos cursos ✔️ 
:+1:

**Comment by Mysfer** [comment]
Está tendo um erro de exibição e inserção dos vídeos secundários nos cursos ✔️
